postgres:
  image: postgres
  restart: always
  environment:
    POSTGRES_USERNAME: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: library
  ports:
    - "15432:5432"
  volumes:
    - /var/lib/postgresql/data
